/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package usolibreriaconversiones;

import libreria.Convertir;

/**
 *
 * @author Montse Caballero
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblRes = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toneladas", "Libras", "Onzas", "Minutos", "Horas", "Días ", "Km/h", "mph ", "Aceleración ", "Libras de fuerza ", "Cal", "eV", "hp", "atm", "bar", "MHz", "Rad", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton1)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRes, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(lblRes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jButton1)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String op = jComboBox1.getSelectedItem().toString(); 
       if (op.equals("Toneladas")){
           if (Convertir.soloContieneDígitos(jTextField1.getText())){
              double res = Convertir.ToneladasKilogramos(Double.parseDouble(jTextField1.getText())); 
              lblRes.setText("resulado : "+res+ " Kg"); 
           } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
           }
       }
       if (op.equals("Libras")){
          if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.LibrasKilogramos(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res+" Kg"); 
          } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
          }
       }
       if (op.equals("Onzas")){
           if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.OnzasGramos(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res+ " Gr"); 
       }
}
       if (op.equals("Minutos")){
           if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.MinutosSegundos(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res+ " S"); 
          } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
          }
       }
       if (op.equals("Horas")){
           if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.HorasSegundos(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res+ " S"); 
          } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
          }
       }
        if (op.equals("Días ")){
            if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.DiaSegundos(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res + " S"); 
          } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
          }
       }
        if (op.equals("Km/h")){
            if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.KmporhoraMporsegundo(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res+ " m/s"); 
          } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
          }
       }
        if (op.equals("mph ")){
            if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.MPHaKMH(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res+ " km/h"); 
          } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
          }
       }
        if (op.equals("Aceleración ")){
            if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.Aceleracion(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res + "m/s");
          } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
          }
       }
        if (op.equals("Libras de Fuerza ")){
            if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.LibrasFuerzaNewtons(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res+ " N");
          } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
          }
       }
        if (op.equals("Cal")){
            if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.CalJul(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res + " J"); 
          } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
          }
       }
        if (op.equals("eV")){
            if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.eVJul(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res+ " J"); 
          } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
          }
       }
        if (op.equals("hp")){
            if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.hpVatio(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res+ " W"); 
          } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
          }
       }
        if (op.equals("atm")){
            if (Convertir.soloContieneDígitos(jTextField1.getText())){
        double res = Convertir.atmPa(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res+ " Pa"); 
          } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
          }
       }
        if (op.equals("bar")){
            if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.barPa(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res + " Pa"); 
          } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
          }
       }
        if (op.equals("MHz")){
            if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.MHzaHz(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res+ " Hz"); 
          } else {
               lblRes.setText("No se pueden hacer cáclulos con letras"); 
          }
       }
        if (op.equals("Rad")){
            if (Convertir.soloContieneDígitos(jTextField1.getText())){
          double res = Convertir.RadGrados(Double.parseDouble(jTextField1.getText())); 
          lblRes.setText("resultado: "+res + "º"); 
          } else {
               lblRes.setText("No se pueden hacer cálculos con letras"); 
          } 
       }            
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblRes;
    // End of variables declaration//GEN-END:variables
}
